
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zon: GMT+8
  application:
    name: sb_cloud_config_client
#  #RebbitMq
  rabbitmq:
    host: 39.108.85.204
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        myoutput: # 自定义output
          group: girlfriend  #分组 同一组的消息只有一个实例接收
          content-type: application/json #消息发送的格式 发送端指定即可
          destination: sb-cloud-stream
        myinput:  # 自定义input
          destination: sb-cloud-stream
        myoutputto: # 自定义output (回馈使用)
          content-type: application/json #消息发送的格式 发送端指定即可
          destination: sb-cloud-stream-to
        myinputto:  # 自定义input(回馈使用)
          destination: sb-cloud-stream-to

eureka:
  client:
    serviceUrl:
      defaultZone: http://39.108.85.204:8761/eureka/
  instance:
    #注册时使用ip而不是主机名
    prefer-ip-address: true
    #指定此实例的ip
    #ip-address: ip
server:
  port: 9004